export default {
  ADD_TO_CART: '/mobile/add_cart',
  CATEGORIES: '/mobile/categories',
  CHECKOUT: '/mobile/confirm_checkout',
  FILTER_CATEGORY: '/mobile/filter_produk_by_category',
  KABUPATEN: '/mobile/kabupaten',
  KECAMATAN: '/mobile/kecamatan',
  KELURAHAN: '/mobile/kelurahan',
  LOGIN: '/mobile/login',
  NEWS: '/mobile/news',
  PAYMENT_METHOD: '/mobile/jenis_payment',
  PRODUCT_DETAIL: '/mobile/produk_detail',
  PRODUCT_RECOMMENDATION: '/mobile/produk-unggulan',
  PROVINCE: '/mobile/provinsi',
  REGISTER: '/mobile/register',
  SLIDER: '/mobile/slider',
  SPONSOR: '/mobile/sponsor',
  TENANT: '/mobile/tenant',
  TENANT_RECOMMENDATION: '/mobile/tenant-unggulan',
};
